add Indonesia i18n locale
bradymholt/cRonstrue pull request #208
Opened 2021-08-20 16:32 UTC by hasanbasri1993

2021-08-20 16:42 UTC, bradymholt requested changes
Thanks!  I quick request.

2021-08-20 16:42 UTC, bradymholt commented on README.md
> +- id - Indonesia
Could you also line 12 so it notes **27** languages?

2021-08-23 05:28 UTC, hasanbasri1993 commented
i hope, it merge

2021-08-23 12:10 UTC, bradymholt commented
Thanks!

2021-08-23 12:10 UTC, merged